name: Deploy Pages

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.100
      - name: Install Blazor Template
        run: dotnet new -i "Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2"
      - name: Build
        run: dotnet publish -c Release -o ../publish
        working-directory: ./JumjaroWeb
      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mv publish/JumjaroWeb/dist /tmp/deploy
          git init /tmp/deploy
          cd /tmp/deploy
          touch .nojekyll
          echo "jumjaro.org" > CNAME
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -m gh-pages
          auth="${GITHUB_ACTOR}:${{ secrets.ACCESS_TOKEN }}"
          git remote add origin "https://${auth}@github.com/${GITHUB_REPOSITORY}.git"
          git push -f origin gh-pages
